%YAML:1.0


#--------------------------------------------------------------------------------------------
# Camera Parameters
#--------------------------------------------------------------------------------------------
# the parameter style is like ORB-SLAM2

#camera intrinsics
Camera.left.fx: 721.5377
Camera.left.fy: 721.5377
Camera.left.cx: 609.5593
Camera.left.cy: 172.854

Camera.right.fx: 721.5377
Camera.right.fy: 721.5377
Camera.right.cx: 609.5593
Camera.right.cy: 172.854

Camera.left.k1: 0.0
Camera.left.k2: 0.0
Camera.left.p1: 0.0
Camera.left.p2: 0.0

Camera.right.k1: 0.0
Camera.right.k2: 0.0
Camera.right.p1: 0.0
Camera.right.p2: 0.0

# stereo baseline times fx
Camera.bf: 387.5744

# Camera frames per second 
# the system will ignore this and run as fast as possible if you set this as -1
Camera.fps: -1





#--------------------------------------------------------------------------------------------
# Feature Parameters
#--------------------------------------------------------------------------------------------

# valid feature numbers to decide the tracking / init status
numFeatures.initGood: 100
numFeatures.trackingGood: 50
numFeatures.trackingBad: 10

# ORB Extractor: Number of features when initalizing
ORBextractor.nInitFeatures: 300
# ORB Extractor: Number of new features to detect when needs to create a new KF
ORBextractor.nNewFeatures: 100
# ORB Extractor: Scale factor between levels in the scale pyramid 	
ORBextractor.scaleFactor: 1.2
# ORB Extractor: Number of levels in the scale pyramid	
ORBextractor.nLevels: 8
# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast			
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 7


#--------------------------------------------------------------------------------------------
# Map Parameters
#--------------------------------------------------------------------------------------------
Map.activeMap.size: 7

#--------------------------------------------------------------------------------------------
# Loop Closing Parameters
#--------------------------------------------------------------------------------------------

LCD.similarityScoreThreshold.high: 0.94
LCD.similarityScoreThreshold.low: 0.92

# if you want to see the match and reprojection result, please set this as 1
# note that normally the system doesn't need to store KF's image but only the descriptors
# but if you set this as 1, then it needs to store KF's image just for the show
LoopClosing.bShowResult: 0
# the system won't do loop detection 
#   until the number of KFs in database is more than this threshold
LCD.nDatabaseMinSize: 50


#--------------------------------------------------------------------------------------------
# Viewer Parameters
#--------------------------------------------------------------------------------------------

# if you want to see the frame and trajectory in real time, please set this as 1
# note that this will slow down the speed of the system
Viewer.bShow: 0

# some parameters for pangolin
Viewer.KeyFrameSize: 0.1
Viewer.KeyFrameLineWidth: 1
Viewer.GraphLineWidth: 1
Viewer.PointSize:2
Viewer.CameraSize: 0.15
Viewer.CameraLineWidth: 2
Viewer.ViewpointX: 0
Viewer.ViewpointY: -500
Viewer.ViewpointZ: -0.1
Viewer.ViewpointF: 2000


